# Generated by Django 4.1.4 on 2023-01-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
