# Generated by Django 4.1.4 on 2023-01-29 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_personal_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='curriculum',
        ),
    ]
