# Generated by Django 4.1.4 on 2023-01-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_remove_personal_activo_remove_personal_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='curriculum',
            field=models.FileField(blank=True, upload_to='curriculums/', verbose_name='Curriculum'),
        ),
    ]
