# Generated by Django 4.1.4 on 2023-01-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_personal_activo_personal_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='foto',
            field=models.ImageField(blank=True, upload_to='foto/', verbose_name='Foto'),
        ),
    ]
