# Generated by Django 4.1.4 on 2023-01-29 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_alter_personal_activo_alter_personal_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.cargo'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='curriculum',
            field=models.FileField(upload_to='curriculums/', verbose_name='Curriculum'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='foto',
            field=models.ImageField(upload_to='foto/', verbose_name='Foto'),
        ),
    ]
