# Generated by Django 4.1.4 on 2023-01-30 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='anulate',
        ),
    ]
