# Generated by Django 4.1.4 on 2023-01-28 03:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='faltas',
        ),
        migrations.AddField(
            model_name='personal',
            name='falta_des',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripcion de faltas'),
        ),
        migrations.AddField(
            model_name='personal',
            name='n_faltas',
            field=models.IntegerField(blank=True, default=0, verbose_name='Numero de Faltas'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='aportes',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Aportes'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='deficiencias',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Deficiencias'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='foto',
            field=models.ImageField(upload_to='foto/', verbose_name='Foto'),
        ),
    ]
