# Generated by Django 4.1.4 on 2023-01-28 03:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_remove_personal_faltas_personal_falta_des_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='recomendaciones',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Recomendaciones'),
        ),
    ]
