# Generated by Django 4.1.4 on 2023-01-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_personal_recomendaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='n_telefonico',
            field=models.IntegerField(default=12344, verbose_name='Numero de telefono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal',
            name='t_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CI', 'CI'), ('PASAPORTE', 'PASAPORTE'), ('CARNET DE EXTRANGERIA', 'CARNET DE EXTRANJERIA')], default='DNI', max_length=30, verbose_name='Tipo de Documento'),
        ),
    ]
