# Generated by Django 4.1.4 on 2023-01-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_personal_n_telefonico_alter_personal_t_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
