# Generated by Django 4.1.4 on 2023-01-28 22:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_personal_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='curriculum',
            field=models.FileField(blank=True, upload_to='curriculums/', verbose_name='Curriculum'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion del Cargo'),
        ),
    ]
