# Generated by Django 4.1.4 on 2023-01-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_personal_curriculum_alter_cargo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidades',
            name='habilidades',
            field=models.CharField(blank=True, max_length=50, verbose_name='Habilidades'),
        ),
    ]
