# Generated by Django 4.1.4 on 2023-01-29 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_alter_habilidades_habilidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='curriculum',
        ),
    ]
